<nav>
    <ul>
        <li><a href="<?=$this->url(array('action'=>'index', 'controller'=>'index'),null,true)?>">Home</a></li>
        <li><a href="<?=$this->url(array('action'=>'index', 'controller'=>'categoria'),null,true)?>">Categorías</a></li>
        <li><a href="<?=$this->url(array('action'=>'index', 'controller'=>'fabricante'),null,true)?>">Fabricantes</a></li>
        <li><a href="<?=$this->url(array('action'=>'index', 'controller'=>'producto'),null,true)?>">Productos</a></li>
        <li><a href="<?=$this->url(array('action'=>'index', 'controller'=>'venta'),null,true)?>">Ventas</a></li>
        <li class="der"><a href="<?=$this->url(array('action'=>'index', 'controller'=>'reporte'),null,true)?>">Reportes</a></li>
    </ul>
</nav>
