<?= $this->doctype(); ?>
<html lang="en">
    <head>
        <?= $this->headMeta() ?>
        <?= $this->headTitle() ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
        <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <link rel="stylesheet" type="text/css" href="iehacks.css" />
        <![endif]-->

        <!--[if lte IE 7]>
        <link rel="stylesheet" type="text/css" href="ie67hacks.css" />
        <![endif]-->
    </head>
    <body>
        <header>
        <?= $this->render('_cabecera.phtml'); ?>
        
        </header>    
        <br/>
        <div id="content">
            
            <section class="hfeed">
                <?= $this->render('_mensajes.phtml'); ?>
                <article class="hentry">
                    <h2>Login</h2>
                    
                    <?= $this->layout()->content ?>
                </article>
            </section>            
        </div>
        <?= $this->render('_pie.phtml'); ?>
    </body>
</html>